name: Build

on:
  push:
    branches: ["master", "release-v*", "avalonia_port"]
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Build
        run: |
          dotnet workload restore
          dotnet build --configuration Release
      - name: Test
        run: dotnet test Tests/Nodify.Tests/Nodify.Tests.csproj --configuration Release --no-build
