name: Tests

on:
  pull_request:
  push:
    branches: ["avalonia_port"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet test Tests/Nodify.Tests/Nodify.Tests.csproj --configuration Release
